export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  // 추가
  | "Whisper"
  | "FastText"
  | "LangChain"
  | "Chroma"
  | "Airflow"
  | "BigQuery"
  | "Cloud Composer"
  | "Cloud Storage"
  | "Looker Studio"
  | "Tableau"
  | "Chrome Extension"
  | "Selenium"
  | "KcELECTRA"
  | "Hugging Face"
  | "Data Analysis"
  | "Machine Learning"
  | "Technical Research"
  | "Redash"
  | "Data Visualization"
  | "Natural Language Processing"
  | "Large Language Models"
  | "RAG"
  | "Transformer"
  | "GPT"
  | "LLM"
  | "Deep Learning"
  | "Accessibility"
  | "AI"
  | "Excel"
  | "Data Cleansing"
  | "Data Analysis"
  | "Data Automation"
  | "Power Automate"
  | "SAP BW";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  // 추가
  | "AI"
  | "Speech Recognition"
  | "Web Service"
  | "Accessibility"
  | "Developer Tool"
  | "LLM"
  | "RAG"
  | "NLP"
  | "Chrome Extension";

export type ValidExpType = "Personal" | "Professional";

export type ValidExperienceType =
  | "Internships"
  | "Campus Activities"
  | "External Activities";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "achievements"
  | "contact"
  | "contributions"
  | "resume"
  | "blogs";
